version: "2"
name: blabla
canonical: blabla
author: admin
status: private
description: blabla
image: ""
keywords:
- mitko
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      blabla:
        destination: ($ project $)/terraform/($ environment $)/blabla.tf
        path: terraform/default/blabla.tf.sample
