version: "2"
name: stacktouse
canonical: stacktouse
author: flo_test
status: private
description: stacktouse
image: ""
keywords:
- stacktouse
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      stacktouse:
        destination: ($ project $)/terraform/default/($ environment $)/stacktouse.tf
        path: terraform/default/stacktouse.tf.sample
