module "reuse_stack" {
  # aws_instance_DZhsp_instance_type = "t3.small"
  # aws_instance_FbcwH_instance_type = "c5.2xlarge"
  # aws_instance_GdTHC_instance_type = "m3.medium"
  # aws_instance_HdOUJ_instance_type = "t3.medium"
  # aws_instance_JLXEc_instance_type = "c5.2xlarge"
  # aws_instance_PYDQX_instance_type = "t3.small"
  # aws_instance_RUcgm_instance_type = "t2.small"
  # aws_instance_RiVRt_instance_type = "t3.small"
  # aws_instance_TPGtW_instance_type = "t3.small"
  # aws_instance_dzpSj_instance_type = "t3.small"
  # aws_instance_pOPaJ_instance_type = "t2.small"
  # aws_instance_qhkxR_instance_type = "c5.2xlarge"
  # aws_instance_tshaD_instance_type = "t2.micro"
  # aws_instance_xCcCf_instance_type = "c5.2xlarge"
  # aws_instance_xlDNY_instance_type = "t3.small"
  # aws_instance_zOapq_instance_type = "t2.medium"
  # aws_instance_zRfXG_instance_type = "t3.small"
  source = "module-reuse_stack"
}

