version: "2"
name: gcpbuck
canonical: gcpbuck
author: admin
status: private
description: gcpbuck
image: ""
keywords:
- gcpbuck
- provider:google
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      gcpbuck:
        destination: ($ project $)/terraform/($ environment $)/gcpbuck.tf
        path: terraform/default/gcpbuck.tf.sample
