version: "2"
name: stackonly
canonical: stackonly
author: flo_test
status: private
description: stackonly
image: ""
keywords:
- stackonly
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      stackonly:
        destination: ($ project $)/default/terraform/($ environment $)/stackonly.tf
        path: terraform/default/stackonly.tf.sample
