version: "2"
name: stackonly5
canonical: stackonly5
author: flo_test
status: private
description: stackonly5
image: ""
keywords:
- stackonly5
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
