#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "myapp" {
  source = "./module-sample"

  cronjobs = {
    quiz = {
      cpu        = 256
      entrypoint = "/bin/php"
      memory     = 1024
      schedule   = "*/30 * * * ? *"
    }
  }
  env          = var.env
  organization = var.organization
  project      = var.project
}

