version: "2"
name: test_stack
canonical: test_stack
author: admin
status: private
description: descr
image: ""
keywords:
- crappy
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
