module "azuretestextbe" {
  # azurerm_resource_group__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform__tc_tags_cycloid_io                                                                                                        = "true"
  # azurerm_resource_group__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_location                                                                                                                   = "francecentral"
  # azurerm_resource_group__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_name                                                                                                                       = "cycloid-terraform"
  # azurerm_resource_group__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_tc_category                                                                                                                = "base"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_access_tier                                                     = "Hot"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_account_kind                                                    = "StorageV2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_account_replication_type                                        = "RAGRS"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_account_tier                                                    = "Standard"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_allow_blob_public_access                                        = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_enable_https_traffic_only                                       = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_location                                                        = "francecentral"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_min_tls_version                                                 = "TLS1_2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_name                                                            = "cycloiddemotfstate"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_network_rules_bypass                                            = ["AzureServices"]
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_network_rules_default_action                                    = "Allow"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_hour_metrics_enabled                           = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_hour_metrics_include_apis                      = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_hour_metrics_retention_policy_days             = 7
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_hour_metrics_version                           = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_logging_delete                                 = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_logging_read                                   = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_logging_version                                = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_logging_write                                  = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_minute_metrics_enabled                         = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_queue_properties_minute_metrics_version                         = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_resource_group_name                                             = "cycloid-demo"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_demo_providers_microsoft_storage_storageaccounts_cycloiddemotfstate_tc_category                                                     = "storage"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_access_tier                                                       = "Hot"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_account_kind                                                      = "StorageV2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_account_replication_type                                          = "LRS"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_account_tier                                                      = "Standard"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_enable_https_traffic_only                                         = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_location                                                          = "westeurope"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_min_tls_version                                                   = "TLS1_2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_name                                                              = "cycloidlabtfstate"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_network_rules_bypass                                              = ["AzureServices"]
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_network_rules_default_action                                      = "Allow"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_hour_metrics_enabled                             = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_hour_metrics_include_apis                        = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_hour_metrics_retention_policy_days               = 7
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_hour_metrics_version                             = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_logging_delete                                   = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_logging_read                                     = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_logging_version                                  = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_logging_write                                    = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_minute_metrics_enabled                           = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_queue_properties_minute_metrics_version                           = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_resource_group_name                                               = "cycloid-lab"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_lab_providers_microsoft_storage_storageaccounts_cycloidlabtfstate_tc_category                                                       = "storage"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate__tc_tags_cycloid_io                                            = "true"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_access_tier                                                    = "Hot"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_account_kind                                                   = "StorageV2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_account_replication_type                                       = "LRS"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_account_tier                                                   = "Standard"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_enable_https_traffic_only                                      = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_location                                                       = "francecentral"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_min_tls_version                                                = "TLS1_0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_name                                                           = "cycloidtfstate"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_network_rules_bypass                                           = ["AzureServices"]
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_network_rules_default_action                                   = "Allow"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_hour_metrics_enabled                          = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_hour_metrics_include_apis                     = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_hour_metrics_retention_policy_days            = 7
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_hour_metrics_version                          = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_logging_delete                                = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_logging_read                                  = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_logging_version                               = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_logging_write                                 = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_minute_metrics_enabled                        = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_queue_properties_minute_metrics_version                        = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_resource_group_name                                            = "cycloid-terraform"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_cycloid_terraform_providers_microsoft_storage_storageaccounts_cycloidtfstate_tc_category                                                    = "storage"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests__tc_tags_cycloid_io                                  = "true"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_access_tier                                          = "Hot"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_account_kind                                         = "StorageV2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_account_replication_type                             = "LRS"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_account_tier                                         = "Standard"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_enable_https_traffic_only                            = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_location                                             = "francecentral"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_min_tls_version                                      = "TLS1_0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_name                                                 = "azurettfstatetests"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_network_rules_bypass                                 = ["AzureServices"]
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_network_rules_default_action                         = "Allow"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_hour_metrics_enabled                = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_hour_metrics_include_apis           = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_hour_metrics_retention_policy_days  = 7
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_hour_metrics_version                = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_logging_delete                      = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_logging_read                        = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_logging_version                     = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_logging_write                       = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_minute_metrics_enabled              = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_queue_properties_minute_metrics_version              = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_resource_group_name                                  = "youdeploy-backend-tests"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_azurettfstatetests_tc_category                                          = "storage"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_access_tier                                         = "Hot"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_account_kind                                        = "StorageV2"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_account_replication_type                            = "LRS"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_account_tier                                        = "Standard"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_enable_https_traffic_only                           = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_location                                            = "francecentral"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_min_tls_version                                     = "TLS1_0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_name                                                = "cycloidcostexplorer"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_network_rules_bypass                                = ["AzureServices"]
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_network_rules_default_action                        = "Allow"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_hour_metrics_enabled               = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_hour_metrics_include_apis          = true
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_hour_metrics_retention_policy_days = 7
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_hour_metrics_version               = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_logging_delete                     = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_logging_read                       = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_logging_version                    = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_logging_write                      = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_minute_metrics_enabled             = false
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_queue_properties_minute_metrics_version             = "1.0"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_resource_group_name                                 = "youdeploy-backend-tests"
  # azurerm_storage_account__subscriptions_edce4685_4988_4a09_8b4a_3d5b917022cd_resourcegroups_youdeploy_backend_tests_providers_microsoft_storage_storageaccounts_cycloidcostexplorer_tc_category                                         = "storage"
  source = "./module-azuretestextbe"
}


terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }

  }

  required_version = ">= 1.0"
}


# Cycloid
variable "organization" {}
variable "customer" {}
variable "project" {}
variable "env" {}
	
provider "azurerm" {
	features {}
}
