version: "2"
name: gcp-mitko-test
canonical: gcp-mitko-test
author: admin
status: private
description: testing GCP importing
image: ""
keywords:
- mitko
- test
- provider:google
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
