version: "2"
name: testestestset
canonical: testestestset
author: admin
status: private
description: testestestset
image: ""
keywords:
- testestestset
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      testestestset:
        destination: ($ project $)/default/terraform/($ environment $)/testestestset.tf
        path: default/terraform/testestestset.tf.sample
