version: "2"
name: stackproj
canonical: stackproj
author: flo_test
status: private
description: stackproj
image: ""
keywords:
- stackproj
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
