version: "2"
name: stackandproject
canonical: stackandproject
author: flo_test
status: private
description: stackandproject
image: ""
keywords:
- stackandproject
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      stackandproject:
        destination: ($ project $)/terraform/default/($ environment $)/stackandproject.tf
        path: terraform/default/stackandproject.tf.sample
