version: "2"
name: testaaa
canonical: testaaa
author: admin
status: private
description: aaaa
image: ""
keywords:
- aaa
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      testaaa:
        destination: ($ project $)/default/terraform/($ environment $)/testaaa.tf
        path: default/terraform/testaaa.tf.sample
