version: "2"
name: azureextbe
canonical: azureextbe
author: admin
status: private
description: azureextbe
image: ""
keywords:
- azureextbe
- provider:azure
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      azureextbe:
        destination: ($ project $)/terraform/($ environment $)/azureextbe.tf
        path: terraform/default/azureextbe.tf.sample
