version: "2"
name: azurefail5
canonical: azurefail5
author: admin
status: private
description: azurefail5
image: ""
keywords:
- azurefail5
- provider:azure
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      azurefail5:
        destination: ($ project $)/terraform/($ environment $)/azurefail5.tf
        path: terraform/default/azurefail5.tf.sample
