version: "2"
name: azurestackandproject3
canonical: azurestackandproject3
author: admin
status: private
description: azurestackandproject3
image: ""
keywords:
- azurestackandproject3
- provider:azure
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      azurestackandproject3:
        destination: ($ project $)/terraform/($ environment $)/azurestackandproject3.tf
        path: terraform/default/azurestackandproject3.tf.sample
