version: "2"
name: azurefail4
canonical: azurefail4
author: admin
status: private
description: azurefail4
image: ""
keywords:
- azurefail4
- provider:azure
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      azurefail4:
        destination: ($ project $)/terraform/($ environment $)/azurefail4.tf
        path: terraform/default/azurefail4.tf.sample
