version: "2"
name: stacktest
canonical: stacktest
author: flo_test
status: private
description: stacktest
image: ""
keywords:
- stacktest
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
