version: "2"
name: gaelstack1
canonical: gaelstack1
author: admin
status: private
description: test
image: ""
keywords:
- test
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      gaelstack1:
        destination: ($ project $)/default/terraform/($ environment $)/gaelstack1.tf
        path: default/terraform/gaelstack1.tf.sample
