version: "2"
name: storage
canonical: storage
author: admin
status: private
description: storage
image: ""
keywords:
- storage
- provider:azure
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
      storage:
        destination: ($ project $)/terraform/($ environment $)/storage.tf
        path: terraform/default/storage.tf.sample
