version: "2"
name: gcpbucket2
canonical: gcpbucket2
author: admin
status: private
description: gcpbucket2
image: ""
keywords:
- gcpbucket2
- provider:google
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      gcpbucket2:
        destination: ($ project $)/terraform/($ environment $)/gcpbucket2.tf
        path: terraform/default/gcpbucket2.tf.sample
