version: "2"
name: redisdown
canonical: redisdown
author: flo_test
status: private
description: redisdown
image: ""
keywords:
- redisdown
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
