version: "2"
name: accountstoragetest
canonical: accountstoragetest
author: admin
status: private
description: accountstoragetest
image: ""
keywords:
- accountstoragetest
- provider:azure
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      accountstoragetest:
        destination: ($ project $)/terraform/($ environment $)/accountstoragetest.tf
        path: terraform/default/accountstoragetest.tf.sample
      config:
        destination: ($ project $)/terraform/($ environment $)/config.tf
        path: terraform/default/config.tf.sample
