version: "2"
name: aws_security_group
canonical: aws_security_group
author: flo_test
status: private
description: aws_security_group
image: ""
keywords:
- aws_security_group
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      aws_security_group:
        destination: ($ project $)/default/terraform/($ environment $)/aws_security_group.tf
        path: terraform/default/aws_security_group.tf.sample
