version: "2"
name: stackonly2
canonical: stackonly2
author: flo_test
status: private
description: stackonly2
image: ""
keywords:
- stackonly2
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      stackonly2:
        destination: ($ project $)/default/terraform/($ environment $)/stackonly2.tf
        path: terraform/default/stackonly2.tf.sample
