version: "2"
name: steve-aws-worker
canonical: steve-aws-worker
author: admin
status: private
description: Trying to replicate the external worker CloudFormation deployment as
  terraform code.
image: ""
keywords:
- concourse
- aws
- worker
- terraform
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
