version: "2"
name: awstfstate
canonical: awstfstate
author: admin
status: private
description: awstfstate
image: ""
keywords:
- awstfstate
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      awstfstate:
        destination: ($ project $)/terraform/($ environment $)/awstfstate.tf
        path: terraform/default/awstfstate.tf.sample
