version: "2"
name: Mitko test 5
canonical: mitko_test_5
author: admin
status: private
description: Mitko testing again
image: ""
keywords:
- mitko
- test
- provider:google
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      mitko_test_5:
        destination: ($ project $)/terraform/($ environment $)/mitko_test_5.tf
        path: terraform/default/mitko_test_5.tf.sample
