version: "2"
name: azureprovider
canonical: azureprovider
author: admin
status: private
description: azureprovider
image: ""
keywords:
- azureprovider
- provider:azure
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      azureprovider:
        destination: ($ project $)/terraform/($ environment $)/azureprovider.tf
        path: terraform/default/azureprovider.tf.sample
