version: "2"
name: eip
canonical: eip
author: florian
status: private
description: eip
image: ""
keywords:
- eip
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      eip:
        destination: ($ project $)/default/terraform/($ environment $)/eip.tf
        path: default/terraform/eip.tf.sample
