version: "2"
name: testemail
canonical: testemail
author: flo_test
status: private
description: testemail
image: ""
keywords:
- testemail
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      testemail:
        destination: ($ project $)/default/terraform/($ environment $)/testemail.tf
        path: default/terraform/testemail.tf.sample
