version: "2"
name: stackonly3
canonical: stackonly3
author: flo_test
status: private
description: stackonly3
image: ""
keywords:
- stackonly3
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      stackonly3:
        destination: ($ project $)/default/terraform/($ environment $)/stackonly3.tf
        path: terraform/default/stackonly3.tf.sample
