version: "2"
name: gcpimportall
canonical: gcpimportall
author: admin
status: private
description: gcpimportall
image: ""
keywords:
- gcpimportall
- provider:google
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
